
name: Monitoreo cada 3 horas

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write # Permiso para que GitHub pueda guardar los cambios en el CSV

jobs:
  medir:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests
        
      - name: Ejecutar script de medición
        env:
          APP_USER: ${{ secrets.APP_USER }}
          APP_PASS: ${{ secrets.APP_PASS }}
        run: python monitor.py

      - name: Guardar el CSV actualizado en el repositorio
        run: |
          git config --global user.name "Monitor Bot"
          git config --global user.email "bot@github.com"
          git add tiempos_servidor.csv
          # Solo hace commit si hubo cambios en el archivo
          git diff --quiet && git diff --staged --quiet || (git commit -m "Nueva medición guardada" && git push)
